### PR TITLE
Fixed license and bug which was detected by user

### PR DESCRIPTION
**Pull request by danielmarbach**

### CODE REVIEW

**Comment by danielmarbach** [comment]
@remogloor could you please release a new version of the extension after you merged it?

**Comment by LockTar** [comment]
Thank you @danielmarbach and @remogloor. I will wait for the new release and will respond the results.

**Comment by LockTar** [comment]
Will this also push an update of the nuget package?

**Comment by danielmarbach** [comment]
Yes this should already be available as alpha release on nuget.

**Pull request merged**
